name: build and test

on:
  push:
    branches:
      - develop
    paths-ignore:
      - "docs/**"
      - "README.md"
  pull_request:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test_cpu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.7", "3.8"]
        include:
          - python-version: "3.7"
            os: windows-latest
            gdal-whl-url: https://download.lfd.uci.edu/pythonlibs/archived/cp37/GDAL-3.3.3-cp37-cp37m-win_amd64.whl
          - python-version: "3.7"
            os: ubuntu-latest
            gdal-whl-url: https://versaweb.dl.sourceforge.net/project/gdal-wheels-for-linux/GDAL-3.4.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl
          - python-version: "3.8"
            os: windows-latest
            gdal-whl-url: https://download.lfd.uci.edu/pythonlibs/archived/GDAL-3.3.3-cp38-cp38-win_amd64.whl
          - python-version: "3.8"
            os: ubuntu-latest
            gdal-whl-url: https://versaweb.dl.sourceforge.net/project/gdal-wheels-for-linux/GDAL-3.4.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: python -m pip install pip --upgrade --user
      - name: Install PaddlePaddle
        run: python -m pip install paddlepaddle==2.3.1 -i https://mirror.baidu.com/pypi/simple
      - name: Install PaddleRS
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -e .
      - name: Install GDAL
        run: python -m pip install ${{ matrix.gdal-whl-url }}
      - name: Run unittests
        run: |
          cd tests
          bash run_fast_tests.sh
        shell: bash

  build_and_test_cuda102:
    runs-on: ubuntu-18.04
    container:
      image: pytorch/pytorch:1.9.0-cuda10.2-cudnn7-devel
    steps:
      - uses: actions/checkout@v3
      - name: Fetch GPG keys
        run: |
          apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub
          apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub
      - name: Upgrade pip
        run: python -m pip install pip --upgrade --user
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6 -y
      - name: Install PaddlePaddle
        run: python -m pip install paddlepaddle-gpu==2.3.1 -i https://mirror.baidu.com/pypi/simple
      - name: Install PaddleRS
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -e .
          python --version
      - name: Install GDAL
        run: python -m pip install https://versaweb.dl.sourceforge.net/project/gdal-wheels-for-linux/GDAL-3.4.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl
      # Do not run unittests, because there is NO GPU in the machine.
      # - name: Run unittests
      #   run: |
      #     cd tests
      #     bash run_fast_tests.sh
      #   shell: bash